all: source/PLUSPEOPLE/PesaPi/Configuration.java source/PLUSPEOPLE/PesaPi/PesaPi.java source/PLUSPEOPLE/PesaPi/Payment.java
	javac -d build/ source/PLUSPEOPLE/PesaPi/Configuration.java source/PLUSPEOPLE/PesaPi/PesaPi.java source/PLUSPEOPLE/PesaPi/Payment.java

